global:
  resolve_timeout: 1m

route:
  receiver: 'telegram'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 2h
  group_by: ['alertname']

receivers:
- name: 'telegram'
  webhook_configs:
  - url: 'https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage'
    send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname'] 