version: '3.9'

services:
  bot:
    build: .
    container_name: present-bot
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - DB_NAME=${POSTGRES_DB:-schoolbot}
      - DB_USER=${POSTGRES_USER:-schoolbot}
      - DB_PASS=${POSTGRES_PASSWORD:-schoolbot}
      - DB_HOST=postgres
      - DB_PORT=5432
      - REDIS_DSN=${REDIS_URL:-redis://redis:6379/0}
      - ADMIN_IDS=${ADMIN_IDS}
      - GLITCHTIP_DSN=${GLITCHTIP_DSN}
      - ENV=${ENVIRONMENT:-prod}
      - KEEP_DAYS=${KEEP_DAYS:-14}
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    ports:
      - "8080:8080"  # Health check endpoint
    volumes:
      - ./app:/app/app
      - ./scripts:/app/scripts
      - ./migrations:/app/migrations
      - ./alembic.ini:/app/alembic.ini
    networks:
      - shared-net
      - schoolbot_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:15-alpine
    container_name: present-bot-postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-schoolbot}
      - POSTGRES_USER=${POSTGRES_USER:-schoolbot}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-schoolbot}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - schoolbot_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-schoolbot}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: present-bot-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - shared-net
      - schoolbot_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # GlitchTip - лёгкий мониторинг ошибок
  glitchtip:
    image: glitchtip/glitchtip:3.5.0
    container_name: present-bot-glitchtip
    depends_on:
      - postgres
      - redis
    environment:
      SECRET_KEY: "CHANGE_ME_32_random_chars_here_12345"
      # Postgres
      DATABASE_URL: postgresql://${POSTGRES_USER:-schoolbot}:${POSTGRES_PASSWORD:-schoolbot}@postgres:5432/${POSTGRES_DB:-schoolbot}
      # Redis
      REDIS_URL: redis://redis:6379/1
      # Адрес инстанса (для ссылок в письмах)
      GLITCHTIP_URL_PREFIX: http://glitchtip:8000
      # Отключаем GC для экономии RAM
      MEM_GC_DISABLED: "true"
    ports:
      - "9000:8000"          # внешнее WEB-GUI
    volumes:
      - glitchtip_data:/var/lib/glitchtip   # вложения
    restart: unless-stopped
    networks:
      - schoolbot_network

  # Prometheus - сбор метрик
  prometheus:
    image: prom/prometheus:v2.48.1
    container_name: present-bot-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    restart: unless-stopped
    networks:
      - schoolbot_network

  # Grafana - дашборды
  grafana:
    image: grafana/grafana-oss:10.4.2
    container_name: present-bot-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - schoolbot_network

  # Alertmanager - уведомления
  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: present-bot-alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager:/etc/alertmanager
      - alertmanager_data:/alertmanager
    restart: unless-stopped
    networks:
      - schoolbot_network

  # Maintenance - автоматическое обслуживание
  maintenance:
    image: alpine:3.20
    container_name: present-bot-maintenance
    env_file: .env
    volumes:
      - ./scripts:/scripts:ro
      - backups:/backups
      - /var/lib/docker/containers:/var/lib/docker/containers:rw
      - glitchtip_data:/var/lib/glitchtip:rw
    entrypoint: |
      /bin/sh -c "chmod +x /scripts/maintenance.sh && \
                  echo '30 3 * * * /scripts/maintenance.sh' | crontab - && \
                  crond -f -L /var/log/cron.log"
    restart: unless-stopped
    networks:
      - schoolbot_network

volumes:
  postgres_data:
  glitchtip_data:
  prometheus_data:
  grafana_data:
  alertmanager_data:
  backups:

networks:
  shared-net:
    external: true
  schoolbot_network:
    name: schoolbot_network
