"""add user theme

Revision ID: 003
Revises: 002
Create Date: 2024-01-01 12:00:00.000000

"""

import sqlalchemy as sa
from sqlalchemy import text

from alembic import op

# revision identifiers, used by Alembic.
revision = "003"
down_revision = "002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Проверяем, существует ли уже колонка theme
    connection = op.get_bind()
    result = connection.execute(text("""
        SELECT column_name 
        FROM information_schema.columns 
        WHERE table_name = 'users' AND column_name = 'theme'
    """))
    
    if not result.fetchone():
        op.add_column("users", sa.Column("theme", sa.String(), server_default="light"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "theme")
    # ### end Alembic commands ###
