#!/bin/bash

# Скрипт для проверки работы SchoolBot на сервере
# Использование: ./scripts/server_check.sh

echo "🔍 Проверка работы SchoolBot на сервере..."

# Проверка подключения к серверу
echo "📡 Проверка подключения к серверу..."
if ping -c 1 89.169.38.246 > /dev/null 2>&1; then
    echo "✅ Сервер доступен"
else
    echo "❌ Сервер недоступен"
    exit 1
fi

# Команды для выполнения на сервере
echo "📋 Команды для выполнения на сервере:"
echo ""
echo "1. Подключение к серверу:"
echo "   ssh root@89.169.38.246"
echo ""
echo "2. Проверка статуса ботов:"
echo "   systemctl status schoolbot*"
echo ""
echo "3. Проверка логов ботов:"
echo "   journalctl -u schoolbot -f"
echo "   journalctl -u schoolbot2 -f"
echo "   journalctl -u schoolbot3 -f"
echo ""
echo "4. Проверка процессов:"
echo "   ps aux | grep python"
echo "   ps aux | grep schoolbot"
echo ""
echo "5. Проверка портов:"
echo "   netstat -tlnp | grep :8081"
echo "   netstat -tlnp | grep :8082"
echo "   netstat -tlnp | grep :8083"
echo ""
echo "6. Проверка Docker контейнеров:"
echo "   docker ps"
echo "   docker logs schoolbot"
echo ""
echo "7. Проверка базы данных:"
echo "   docker exec -it postgres psql -U schoolbot -d schoolbot -c 'SELECT COUNT(*) FROM users;'"
echo ""
echo "8. Проверка Redis:"
echo "   docker exec -it redis redis-cli ping"
echo "   docker exec -it redis redis-cli info"
echo ""
echo "9. Проверка мониторинга:"
echo "   curl http://localhost:8081/health"
echo "   curl http://localhost:8082/health"
echo "   curl http://localhost:8083/health"
echo ""
echo "10. Проверка метрик:"
echo "    curl http://localhost:8081/metrics"
echo "    curl http://localhost:8082/metrics"
echo "    curl http://localhost:8083/metrics"
echo ""
echo "11. Проверка нагрузки:"
echo "    htop"
echo "    iostat"
echo "    free -h"
echo ""
echo "12. Проверка дискового пространства:"
echo "    df -h"
echo "    du -sh /opt/schoolbot/*"
echo ""
echo "13. Проверка конфигурации:"
echo "    cat /opt/schoolbot/.env"
echo "    ls -la /opt/schoolbot/"
echo ""
echo "14. Перезапуск ботов:"
echo "    systemctl restart schoolbot"
echo "    systemctl restart schoolbot2"
echo "    systemctl restart schoolbot3"
echo ""
echo "15. Проверка автозапуска:"
echo "    systemctl is-enabled schoolbot"
echo "    systemctl is-enabled schoolbot2"
echo "    systemctl is-enabled schoolbot3"
echo ""
echo "16. Проверка сетевых соединений:"
echo "    ss -tlnp | grep :808"
echo "    lsof -i :8081"
echo "    lsof -i :8082"
echo "    lsof -i :8083"
echo ""
echo "17. Проверка логов приложения:"
echo "    tail -f /opt/schoolbot/logs/bot.log"
echo "    tail -f /opt/schoolbot/logs/error.log"
echo ""
echo "18. Проверка производительности:"
echo "    docker stats"
echo "    top -p \$(pgrep -f schoolbot)"
echo ""
echo "19. Проверка резервных копий:"
echo "    ls -la /opt/schoolbot/backups/"
echo "    du -sh /opt/schoolbot/backups/"
echo ""
echo "20. Проверка обновлений:"
echo "    cd /opt/schoolbot && git status"
echo "    cd /opt/schoolbot && git log --oneline -5"
echo ""
echo "📊 Для мониторинга в реальном времени:"
echo "   watch -n 5 'systemctl status schoolbot*'"
echo "   watch -n 5 'ps aux | grep python | grep schoolbot'"
echo "   watch -n 5 'docker stats --no-stream'"
echo ""
echo "🔧 Для настройки распределения нагрузки:"
echo "   nano /etc/nginx/sites-available/schoolbot"
echo "   systemctl reload nginx"
echo "   nginx -t"
echo ""
echo "📈 Для просмотра метрик Grafana:"
echo "   http://89.169.38.246:3000"
echo "   Логин: admin"
echo "   Пароль: admin"
echo ""
echo "📊 Для просмотра метрик Prometheus:"
echo "   http://89.169.38.246:9090"
echo ""
echo "✅ Проверка завершена!" 